Add a script for testing deployment on test
threshold-network/merkle-distribution pull request #17
Opened 2022-07-08 14:16 UTC by theref

2022-07-12 07:58 UTC, manumonti commented
Some of the commits of this PR has been already merged in #13, so it's hard to review since there is a lot of noise.

Could you please rebase theref:deploy branch to threshold-network:main in order to this PR only shows the actual changes?

2022-07-14 17:06 UTC, manumonti requested changes
As I see, we should merge finish and merge #18 before merging this PR.

2022-07-14 17:06 UTC, manumonti commented on deploy/deploy.js
> +    const args = [tokenContract, rewardsHolder, owner];
If we merge #18, the arguments of the constructor must include TokenStaking contract address.

2022-07-14 17:36 UTC, manumonti commented on deploy/deploy.js
> +    const args = [tokenContract, rewardsHolder, owner];
Finally #18 won't be merged

https://github.com/threshold-network/merkle-distribution/pull/18#issuecomment-1184720318

2022-07-14 17:36 UTC, manumonti approved these changes
LGTM

2022-07-15 08:56 UTC, cygnusv approved these changes

2022-07-15 09:00 UTC, merged